### ISSUE TITLE
Consider adding `__pycache__` to `.gitignore`

### ISSUE THREAD

**Issue by oogl** [PennyHow/schengulator#1]
Hi! I can see that this repo didn't get any updates for more than 2 years, but it still seems important to mention this.

`__pycache__` folder might potentially contain sensitive information that you wouldn't want to disclose to the outer world. In your case, it is just your OS username `pho`, but it could be more than that.

You could use the standard GitHub `.gitignore` [template for projects in Python](https://github.com/github/gitignore/blob/main/Python.gitignore) or check out gitignore.io website

P.S. The deleted info will still be saved in the history of commits, and it could be quite problematic to fully get rid of it

**Comment by PennyHow** [comment]
Thank you so much for pointing this out. Normally I am pretty good at making sure sensitive files like these are not included, but looks like this repo slipped through the net. I'll remove them straight away.

**Comment by PennyHow** [comment]
I've deleted all previous commits and made a fresh release that does not include the sensitive files. Thanks so much again for bringing this to my attention

**Comment by oogl** [comment]
No worries :) Glad to help!
